//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class albumsD
    {
        public int id { get; set; }
        public string nameA { get; set; }
        public string author { get; set; }
        public int genre_id { get; set; }
    }
}
